package com.arrow.dws.adapter.render;

import com.arrow.dws.domain.model.Artifact;
import com.arrow.dws.domain.model.ArtifactKind;
import com.arrow.dws.domain.model.Design;
import com.arrow.dws.domain.model.DesignDocument;
import com.arrow.dws.domain.port.ArtifactRenderer;

import org.springframework.stereotype.Component;

/**
 * A document filed against the design, delivered as a PDF.
 *
 * <p>The POC holds documents as metadata — a name, a kind, a size — and no
 * bytes. So this renders a cover sheet describing the document rather than
 * pretending to reproduce its contents. When real bytes exist, this class
 * either streams them or converts them, and nothing outside it changes.
 */
@Component
public class DocumentPdfRenderer extends PdfWriter implements ArtifactRenderer {

    @Override
    public ArtifactKind handles() {
        return ArtifactKind.DOCUMENT;
    }

    @Override
    public byte[] render(Design design, Artifact artifact) {
        DesignDocument document = design.documents().stream()
                .filter(d -> d.name().equals(artifact.sourceId()))
                .findFirst()
                .orElseThrow(() -> new IllegalStateException(
                        "Artifact " + artifact.id() + " refers to unknown document " + artifact.sourceId()));

        return document(design, artifact, page -> {
            page.pair("Document", document.name());
            page.pair("Kind", document.kind());
            page.pair("Size", document.sizeLabel());
            page.pair("Last updated", document.updatedLabel());
            page.pair("Visibility", document.visibility().label());
            page.blank();
            page.rule();

            page.heading("About this file", 13);
            page.paragraph("This is a cover sheet generated by the Design Workspace. "
                    + "The proof of concept holds documents as metadata, so the original "
                    + "content is not reproduced here.");
            page.blank();
            page.paragraph("In the delivered system this page is replaced by the document "
                    + "itself, converted to PDF. Nothing about the API changes when that "
                    + "happens: the same identifier, the same media type, the same download.");
        });
    }
}
